[Variables]
@include=#@#variables.ini

[MeasureAudioSmoothed1]
Measure=Calc
Formula=#MinBarValue# + (MeasureAudioRaw1 + MeasureAudioRaw1 + MeasureAudioRaw2)/10
AverageSize=#AverageSize#
MaxValue=2
[MeasureAudioSmoothed2]
Measure=Calc
Formula=#MinBarValue# + (MeasureAudioRaw1 + MeasureAudioRaw2 + MeasureAudioRaw3)/9
AverageSize=#AverageSize#
MaxValue=2
[MeasureAudioSmoothed3]
Measure=Calc
Formula=#MinBarValue# + (MeasureAudioRaw2 + MeasureAudioRaw3 + MeasureAudioRaw4)/8
AverageSize=#AverageSize#
MaxValue=2
[MeasureAudioSmoothed4]
Measure=Calc
Formula=#MinBarValue# + (MeasureAudioRaw3 + MeasureAudioRaw4 + MeasureAudioRaw5)/7
AverageSize=#AverageSize#
MaxValue=2
[MeasureAudioSmoothed5]
Measure=Calc
Formula=#MinBarValue# + (MeasureAudioRaw4 + MeasureAudioRaw5 + MeasureAudioRaw6)/6
AverageSize=#AverageSize#
MaxValue=2
[MeasureAudioSmoothed6]
Measure=Calc
Formula=#MinBarValue# + (MeasureAudioRaw5 + MeasureAudioRaw6 + MeasureAudioRaw7)/5
AverageSize=#AverageSize#
MaxValue=2
[MeasureAudioSmoothed7]
Measure=Calc
Formula=#MinBarValue# + (MeasureAudioRaw6 + MeasureAudioRaw7 + MeasureAudioRaw8)/4
AverageSize=#AverageSize#
MaxValue=2
[MeasureAudioSmoothed8]
Measure=Calc
Formula=#MinBarValue# + (MeasureAudioRaw7 + MeasureAudioRaw8 + MeasureAudioRaw9)/3.2
AverageSize=#AverageSize#
MaxValue=2
[MeasureAudioSmoothed9]
Measure=Calc
Formula=#MinBarValue# + (MeasureAudioRaw8 + MeasureAudioRaw9 + MeasureAudioRaw10)/3
;2.25
AverageSize=#AverageSize#
MaxValue=2
[MeasureAudioSmoothed10]
Measure=Calc
Formula=#MinBarValue# + (MeasureAudioRaw9 + MeasureAudioRaw10 + MeasureAudioRaw11)/3
;1.75
AverageSize=#AverageSize#
MaxValue=2
[MeasureAudioSmoothed11]
Measure=Calc
Formula=#MinBarValue# + (MeasureAudioRaw10 + MeasureAudioRaw11 + MeasureAudioRaw12)/3.1
;2
AverageSize=#AverageSize#
MaxValue=2
[MeasureAudioSmoothed12]
Measure=Calc
Formula=#MinBarValue# + (MeasureAudioRaw11 + MeasureAudioRaw12 + MeasureAudioRaw13)/3
;2.5
AverageSize=#AverageSize#
MaxValue=2
[MeasureAudioSmoothed13]
Measure=Calc
Formula=#MinBarValue# + (MeasureAudioRaw12 + MeasureAudioRaw13 + MeasureAudioRaw14)/3
AverageSize=#AverageSize#
MaxValue=2
[MeasureAudioSmoothed14]
Measure=Calc
Formula=#MinBarValue# + (MeasureAudioRaw13 + MeasureAudioRaw14 + MeasureAudioRaw15)/3
AverageSize=#AverageSize#
MaxValue=2
[MeasureAudioSmoothed15]
Measure=Calc
Formula=#MinBarValue# + (MeasureAudioRaw14 + MeasureAudioRaw15 + MeasureAudioRaw16)/3
AverageSize=#AverageSize#
MaxValue=2
[MeasureAudioSmoothed16]
Measure=Calc
Formula=#MinBarValue# + (MeasureAudioRaw15 + MeasureAudioRaw16 + MeasureAudioRaw17)/3
;3.25
AverageSize=#AverageSize#
MaxValue=2
[MeasureAudioSmoothed17]
Measure=Calc
Formula=#MinBarValue# + (MeasureAudioRaw16 + MeasureAudioRaw17 + MeasureAudioRaw18)/3
;3.25
AverageSize=#AverageSize#
MaxValue=2
[MeasureAudioSmoothed18]
Measure=Calc
Formula=#MinBarValue# + (MeasureAudioRaw17 + MeasureAudioRaw18 + MeasureAudioRaw19)/3
AverageSize=#AverageSize#
MaxValue=2
[MeasureAudioSmoothed19]
Measure=Calc
Formula=#MinBarValue# + (MeasureAudioRaw18 + MeasureAudioRaw19 + MeasureAudioRaw20)/3
AverageSize=#AverageSize#
MaxValue=2
[MeasureAudioSmoothed20]
Measure=Calc
Formula=#MinBarValue# + (MeasureAudioRaw19 + MeasureAudioRaw20 + MeasureAudioRaw21)/3
AverageSize=#AverageSize#
MaxValue=2
[MeasureAudioSmoothed21]
Measure=Calc
Formula=#MinBarValue# + (MeasureAudioRaw20 + MeasureAudioRaw21 + MeasureAudioRaw22)/3
AverageSize=#AverageSize#
MaxValue=2
[MeasureAudioSmoothed22]
Measure=Calc
Formula=#MinBarValue# + (MeasureAudioRaw21 + MeasureAudioRaw22 + MeasureAudioRaw23)/3
AverageSize=#AverageSize#
MaxValue=2
[MeasureAudioSmoothed23]
Measure=Calc
Formula=#MinBarValue# + (MeasureAudioRaw22 + MeasureAudioRaw23 + MeasureAudioRaw24)/3
AverageSize=#AverageSize#
MaxValue=2
[MeasureAudioSmoothed24]
Measure=Calc
Formula=#MinBarValue# + (MeasureAudioRaw23 + MeasureAudioRaw24 + MeasureAudioRaw25)/3
AverageSize=#AverageSize#
MaxValue=2
[MeasureAudioSmoothed25]
Measure=Calc
Formula=#MinBarValue# + (MeasureAudioRaw24 + MeasureAudioRaw25 + MeasureAudioRaw26)/3
AverageSize=#AverageSize#
MaxValue=2
[MeasureAudioSmoothed26]
Measure=Calc
Formula=#MinBarValue# + (MeasureAudioRaw25 + MeasureAudioRaw26 + MeasureAudioRaw27)/3
AverageSize=#AverageSize#
MaxValue=2
[MeasureAudioSmoothed27]
Measure=Calc
Formula=#MinBarValue# + (MeasureAudioRaw26 + MeasureAudioRaw27 + MeasureAudioRaw28)/3
AverageSize=#AverageSize#
MaxValue=2
[MeasureAudioSmoothed28]
Measure=Calc
Formula=#MinBarValue# + (MeasureAudioRaw27 + MeasureAudioRaw28 + MeasureAudioRaw29)/3
AverageSize=#AverageSize#
MaxValue=2
[MeasureAudioSmoothed29]
Measure=Calc
Formula=#MinBarValue# + (MeasureAudioRaw28 + MeasureAudioRaw29 + MeasureAudioRaw30)/3
AverageSize=#AverageSize#
MaxValue=2
[MeasureAudioSmoothed30]
Measure=Calc
Formula=#MinBarValue# + (MeasureAudioRaw29 + MeasureAudioRaw30 + MeasureAudioRaw31)/3
AverageSize=#AverageSize#
MaxValue=2
[MeasureAudioSmoothed31]
Measure=Calc
Formula=#MinBarValue# + (MeasureAudioRaw30 + MeasureAudioRaw31 + MeasureAudioRaw32)/3
AverageSize=#AverageSize#
MaxValue=2
[MeasureAudioSmoothed32]
Measure=Calc
Formula=#MinBarValue# + (MeasureAudioRaw31 + MeasureAudioRaw32 + MeasureAudioRaw33)/3
AverageSize=#AverageSize#
MaxValue=2
[MeasureAudioSmoothed33]
Measure=Calc
Formula=#MinBarValue# + (MeasureAudioRaw32 + MeasureAudioRaw33 + MeasureAudioRaw34)/3
AverageSize=#AverageSize#
MaxValue=2
[MeasureAudioSmoothed34]
Measure=Calc
Formula=#MinBarValue# + (MeasureAudioRaw33 + MeasureAudioRaw34 + MeasureAudioRaw35)/3
AverageSize=#AverageSize#
MaxValue=2
[MeasureAudioSmoothed35]
Measure=Calc
Formula=#MinBarValue# + (MeasureAudioRaw34 + MeasureAudioRaw35 + MeasureAudioRaw36)/3
AverageSize=#AverageSize#
MaxValue=2
[MeasureAudioSmoothed36]
Measure=Calc
Formula=#MinBarValue# + (MeasureAudioRaw35 + MeasureAudioRaw36 + MeasureAudioRaw37)/3
AverageSize=#AverageSize#
MaxValue=2
[MeasureAudioSmoothed37]
Measure=Calc
Formula=#MinBarValue# + (MeasureAudioRaw36 + MeasureAudioRaw37 + MeasureAudioRaw38)/3
AverageSize=#AverageSize#
MaxValue=2
[MeasureAudioSmoothed38]
Measure=Calc
Formula=#MinBarValue# + (MeasureAudioRaw37 + MeasureAudioRaw38 + MeasureAudioRaw39)/3
AverageSize=#AverageSize#
MaxValue=2
[MeasureAudioSmoothed39]
Measure=Calc
Formula=#MinBarValue# + (MeasureAudioRaw38 + MeasureAudioRaw39 + MeasureAudioRaw40)/3
AverageSize=#AverageSize#
MaxValue=2
[MeasureAudioSmoothed40]
Measure=Calc
Formula=#MinBarValue# + (MeasureAudioRaw39 + MeasureAudioRaw40 + MeasureAudioRaw41)/3
AverageSize=#AverageSize#
MaxValue=2
[MeasureAudioSmoothed41]
Measure=Calc
Formula=#MinBarValue# + (MeasureAudioRaw40 + MeasureAudioRaw41 + MeasureAudioRaw42)/3
AverageSize=#AverageSize#
MaxValue=2
[MeasureAudioSmoothed42]
Measure=Calc
Formula=#MinBarValue# + (MeasureAudioRaw41 + MeasureAudioRaw42 + MeasureAudioRaw43)/3
AverageSize=#AverageSize#
MaxValue=2
[MeasureAudioSmoothed43]
Measure=Calc
Formula=#MinBarValue# + (MeasureAudioRaw42 + MeasureAudioRaw43 + MeasureAudioRaw44)/3
AverageSize=#AverageSize#
MaxValue=2
[MeasureAudioSmoothed44]
Measure=Calc
Formula=#MinBarValue# + (MeasureAudioRaw43 + MeasureAudioRaw44 + MeasureAudioRaw45)/3
AverageSize=#AverageSize#
MaxValue=2
[MeasureAudioSmoothed45]
Measure=Calc
Formula=#MinBarValue# + (MeasureAudioRaw44 + MeasureAudioRaw45 + MeasureAudioRaw46)/3
AverageSize=#AverageSize#
MaxValue=2
[MeasureAudioSmoothed46]
Measure=Calc
Formula=#MinBarValue# + (MeasureAudioRaw45 + MeasureAudioRaw46 + MeasureAudioRaw47)/3
AverageSize=#AverageSize#
MaxValue=2
[MeasureAudioSmoothed47]
Measure=Calc
Formula=#MinBarValue# + (MeasureAudioRaw46 + MeasureAudioRaw47 + MeasureAudioRaw48)/3
AverageSize=#AverageSize#
MaxValue=2
[MeasureAudioSmoothed48]
Measure=Calc
Formula=#MinBarValue# + (MeasureAudioRaw47 + MeasureAudioRaw48 + MeasureAudioRaw49)/3
AverageSize=#AverageSize#
MaxValue=2
[MeasureAudioSmoothed49]
Measure=Calc
Formula=#MinBarValue# + (MeasureAudioRaw48 + MeasureAudioRaw49 + MeasureAudioRaw50)/3
AverageSize=#AverageSize#
MaxValue=2
[MeasureAudioSmoothed50]
Measure=Calc
Formula=#MinBarValue# + (MeasureAudioRaw49 + MeasureAudioRaw50 + MeasureAudioRaw51)/3
AverageSize=#AverageSize#
MaxValue=2
[MeasureAudioSmoothed51]
Measure=Calc
Formula=#MinBarValue# + (MeasureAudioRaw50 + MeasureAudioRaw51 + MeasureAudioRaw52)/3
AverageSize=#AverageSize#
MaxValue=2
[MeasureAudioSmoothed52]
Measure=Calc
Formula=#MinBarValue# + (MeasureAudioRaw51 + MeasureAudioRaw52 + MeasureAudioRaw53)/3
AverageSize=#AverageSize#
MaxValue=2
[MeasureAudioSmoothed53]
Measure=Calc
Formula=#MinBarValue# + (MeasureAudioRaw52 + MeasureAudioRaw53 + MeasureAudioRaw54)/3
AverageSize=#AverageSize#
MaxValue=2
[MeasureAudioSmoothed54]
Measure=Calc
Formula=#MinBarValue# + (MeasureAudioRaw53 + MeasureAudioRaw54 + MeasureAudioRaw55)/3
AverageSize=#AverageSize#
MaxValue=2
[MeasureAudioSmoothed55]
Measure=Calc
Formula=#MinBarValue# + (MeasureAudioRaw54 + MeasureAudioRaw55 + MeasureAudioRaw56)/3
AverageSize=#AverageSize#
MaxValue=2
[MeasureAudioSmoothed56]
Measure=Calc
Formula=#MinBarValue# + (MeasureAudioRaw55 + MeasureAudioRaw56 + MeasureAudioRaw57)/3
AverageSize=#AverageSize#
MaxValue=2
[MeasureAudioSmoothed57]
Measure=Calc
Formula=#MinBarValue# + (MeasureAudioRaw56 + MeasureAudioRaw57 + MeasureAudioRaw58)/3
AverageSize=#AverageSize#
MaxValue=2
[MeasureAudioSmoothed58]
Measure=Calc
Formula=#MinBarValue# + (MeasureAudioRaw57 + MeasureAudioRaw58 + MeasureAudioRaw59)/3
AverageSize=#AverageSize#
MaxValue=2
[MeasureAudioSmoothed59]
Measure=Calc
Formula=#MinBarValue# + (MeasureAudioRaw58 + MeasureAudioRaw59 + MeasureAudioRaw60)/3
AverageSize=#AverageSize#
MaxValue=2
[MeasureAudioSmoothed60]
Measure=Calc
Formula=#MinBarValue# + (MeasureAudioRaw59 + MeasureAudioRaw60 + MeasureAudioRaw61)/3
AverageSize=#AverageSize#
MaxValue=2
[MeasureAudioSmoothed61]
Measure=Calc
Formula=#MinBarValue# + (MeasureAudioRaw60 + MeasureAudioRaw61 + MeasureAudioRaw62)/3
AverageSize=#AverageSize#
MaxValue=2
[MeasureAudioSmoothed62]
Measure=Calc
Formula=#MinBarValue# + (MeasureAudioRaw61 + MeasureAudioRaw62 + MeasureAudioRaw63)/3
AverageSize=#AverageSize#
MaxValue=2
[MeasureAudioSmoothed63]
Measure=Calc
Formula=#MinBarValue# + (MeasureAudioRaw62 + MeasureAudioRaw63 + MeasureAudioRaw64)/3
AverageSize=#AverageSize#
MaxValue=2
[MeasureAudioSmoothed64]
Measure=Calc
Formula=#MinBarValue# + (MeasureAudioRaw63 + MeasureAudioRaw64 + MeasureAudioRaw65)/3
AverageSize=#AverageSize#
MaxValue=2
[MeasureAudioSmoothed65]
Measure=Calc
Formula=#MinBarValue# + (MeasureAudioRaw64 + MeasureAudioRaw65 + MeasureAudioRaw66)/3
AverageSize=#AverageSize#
MaxValue=2
[MeasureAudioSmoothed66]
Measure=Calc
Formula=#MinBarValue# + (MeasureAudioRaw65 + MeasureAudioRaw66 + MeasureAudioRaw67)/3
AverageSize=#AverageSize#
MaxValue=2
[MeasureAudioSmoothed67]
Measure=Calc
Formula=#MinBarValue# + (MeasureAudioRaw66 + MeasureAudioRaw67 + MeasureAudioRaw68)/3
AverageSize=#AverageSize#
MaxValue=2
[MeasureAudioSmoothed68]
Measure=Calc
Formula=#MinBarValue# + (MeasureAudioRaw67 + MeasureAudioRaw68 + MeasureAudioRaw69)/3
AverageSize=#AverageSize#
MaxValue=2
[MeasureAudioSmoothed69]
Measure=Calc
Formula=#MinBarValue# + (MeasureAudioRaw68 + MeasureAudioRaw69 + MeasureAudioRaw70)/3
AverageSize=#AverageSize#
MaxValue=2
[MeasureAudioSmoothed70]
Measure=Calc
Formula=#MinBarValue# + (MeasureAudioRaw69 + MeasureAudioRaw70 + MeasureAudioRaw71)/3
AverageSize=#AverageSize#
MaxValue=2
[MeasureAudioSmoothed71]
Measure=Calc
Formula=#MinBarValue# + (MeasureAudioRaw70 + MeasureAudioRaw71 + MeasureAudioRaw72)/3
AverageSize=#AverageSize#
MaxValue=2
[MeasureAudioSmoothed72]
Measure=Calc
Formula=#MinBarValue# + (MeasureAudioRaw71 + MeasureAudioRaw72 + MeasureAudioRaw73)/3
AverageSize=#AverageSize#
MaxValue=2
[MeasureAudioSmoothed73]
Measure=Calc
Formula=#MinBarValue# + (MeasureAudioRaw72 + MeasureAudioRaw73 + MeasureAudioRaw74)/3
AverageSize=#AverageSize#
MaxValue=2
[MeasureAudioSmoothed74]
Measure=Calc
Formula=#MinBarValue# + (MeasureAudioRaw73 + MeasureAudioRaw74 + MeasureAudioRaw75)/3
AverageSize=#AverageSize#
MaxValue=2
[MeasureAudioSmoothed75]
Measure=Calc
Formula=#MinBarValue# + (MeasureAudioRaw74 + MeasureAudioRaw75 + MeasureAudioRaw76)/3
AverageSize=#AverageSize#
MaxValue=2
[MeasureAudioSmoothed76]
Measure=Calc
Formula=#MinBarValue# + (MeasureAudioRaw75 + MeasureAudioRaw76 + MeasureAudioRaw77)/3
AverageSize=#AverageSize#
MaxValue=2
[MeasureAudioSmoothed77]
Measure=Calc
Formula=#MinBarValue# + (MeasureAudioRaw76 + MeasureAudioRaw77 + MeasureAudioRaw78)/3
AverageSize=#AverageSize#
MaxValue=2
[MeasureAudioSmoothed78]
Measure=Calc
Formula=#MinBarValue# + (MeasureAudioRaw77 + MeasureAudioRaw78 + MeasureAudioRaw79)/3
AverageSize=#AverageSize#
MaxValue=2
[MeasureAudioSmoothed79]
Measure=Calc
Formula=#MinBarValue# + (MeasureAudioRaw78 + MeasureAudioRaw79 + MeasureAudioRaw80)/3
AverageSize=#AverageSize#
MaxValue=2
[MeasureAudioSmoothed80]
Measure=Calc
Formula=#MinBarValue# + (MeasureAudioRaw79 + MeasureAudioRaw80 + MeasureAudioRaw81)/3
AverageSize=#AverageSize#
MaxValue=2
[MeasureAudioSmoothed81]
Measure=Calc
Formula=#MinBarValue# + (MeasureAudioRaw80 + MeasureAudioRaw81 + MeasureAudioRaw82)/3
AverageSize=#AverageSize#
MaxValue=2
[MeasureAudioSmoothed82]
Measure=Calc
Formula=#MinBarValue# + (MeasureAudioRaw81 + MeasureAudioRaw82 + MeasureAudioRaw83)/3
AverageSize=#AverageSize#
MaxValue=2
[MeasureAudioSmoothed83]
Measure=Calc
Formula=#MinBarValue# + (MeasureAudioRaw82 + MeasureAudioRaw83 + MeasureAudioRaw84)/3
AverageSize=#AverageSize#
MaxValue=2
[MeasureAudioSmoothed84]
Measure=Calc
Formula=#MinBarValue# + (MeasureAudioRaw83 + MeasureAudioRaw84 + MeasureAudioRaw85)/3
AverageSize=#AverageSize#
MaxValue=2
[MeasureAudioSmoothed85]
Measure=Calc
Formula=#MinBarValue# + (MeasureAudioRaw84 + MeasureAudioRaw85 + MeasureAudioRaw86)/3
AverageSize=#AverageSize#
MaxValue=2
[MeasureAudioSmoothed86]
Measure=Calc
Formula=#MinBarValue# + (MeasureAudioRaw85 + MeasureAudioRaw86 + MeasureAudioRaw87)/3
AverageSize=#AverageSize#
MaxValue=2
[MeasureAudioSmoothed87]
Measure=Calc
Formula=#MinBarValue# + (MeasureAudioRaw86 + MeasureAudioRaw87 + MeasureAudioRaw88)/3
AverageSize=#AverageSize#
MaxValue=2
[MeasureAudioSmoothed88]
Measure=Calc
Formula=#MinBarValue# + (MeasureAudioRaw87 + MeasureAudioRaw88 + MeasureAudioRaw89)/3
AverageSize=#AverageSize#
MaxValue=2
[MeasureAudioSmoothed89]
Measure=Calc
Formula=#MinBarValue# + (MeasureAudioRaw88 + MeasureAudioRaw89 + MeasureAudioRaw90)/3
AverageSize=#AverageSize#
MaxValue=2
[MeasureAudioSmoothed90]
Measure=Calc
Formula=#MinBarValue# + (MeasureAudioRaw89 + MeasureAudioRaw90 + MeasureAudioRaw91)/3
AverageSize=#AverageSize#
MaxValue=2
[MeasureAudioSmoothed91]
Measure=Calc
Formula=#MinBarValue# + (MeasureAudioRaw90 + MeasureAudioRaw91 + MeasureAudioRaw92)/3
AverageSize=#AverageSize#
MaxValue=2
[MeasureAudioSmoothed92]
Measure=Calc
Formula=#MinBarValue# + (MeasureAudioRaw91 + MeasureAudioRaw92 + MeasureAudioRaw93)/3
AverageSize=#AverageSize#
MaxValue=2
[MeasureAudioSmoothed93]
Measure=Calc
Formula=#MinBarValue# + (MeasureAudioRaw92 + MeasureAudioRaw93 + MeasureAudioRaw94)/3
AverageSize=#AverageSize#
MaxValue=2
[MeasureAudioSmoothed94]
Measure=Calc
Formula=#MinBarValue# + (MeasureAudioRaw93 + MeasureAudioRaw94 + MeasureAudioRaw95)/3.1
;4
AverageSize=#AverageSize#
MaxValue=2
[MeasureAudioSmoothed95]
Measure=Calc
Formula=#MinBarValue# + (MeasureAudioRaw94 + MeasureAudioRaw95 + MeasureAudioRaw96)/3.2
;5
AverageSize=#AverageSize#
MaxValue=2
[MeasureAudioSmoothed96]
Measure=Calc
Formula=#MinBarValue# + (MeasureAudioRaw95 + MeasureAudioRaw96 + MeasureAudioRaw97)/3.3
;6
AverageSize=#AverageSize#
MaxValue=2
[MeasureAudioSmoothed97]
Measure=Calc
Formula=#MinBarValue# + (MeasureAudioRaw96 + MeasureAudioRaw97 + MeasureAudioRaw98)/3.4
;7
AverageSize=#AverageSize#
MaxValue=2
[MeasureAudioSmoothed98]
Measure=Calc
Formula=#MinBarValue# + (MeasureAudioRaw97 + MeasureAudioRaw98 + MeasureAudioRaw99)/3.5
;8
AverageSize=#AverageSize#
MaxValue=2
[MeasureAudioSmoothed99]
Measure=Calc
Formula=#MinBarValue# + (MeasureAudioRaw98 + MeasureAudioRaw99 + MeasureAudioRaw100)/3.6
;9
AverageSize=#AverageSize#
MaxValue=2
[MeasureAudioSmoothed100]
Measure=Calc
Formula=#MinBarValue# + (MeasureAudioRaw99 + MeasureAudioRaw100 + MeasureAudioRaw100)/3.7
;10
AverageSize=#AverageSize#
MaxValue=2