[MeterBar0]
Meter=BAR
Group=GroupBarColor
MeasureName=MeasureAudioSmoothed1
X=(8*0.30)R
Y=0
W=(18*0.30)
H=(728*0.30)/2 * 2
BarOrientation=Vertical
[MeterBar1]
Meter=BAR
Group=GroupBarColor
MeasureName=MeasureAudioSmoothed2
X=(8*0.30)R
Y=0
W=(18*0.30)
H=(728*0.30)/2 * 2
BarOrientation=Vertical
[MeterBar2]
Meter=BAR
Group=GroupBarColor
MeasureName=MeasureAudioSmoothed3
X=(8*0.30)R
Y=0
W=(18*0.30)
H=(728*0.30)/2 * 2
BarOrientation=Vertical
[MeterBar3]
Meter=BAR
Group=GroupBarColor
MeasureName=MeasureAudioSmoothed4
X=(8*0.30)R
Y=0
W=(18*0.30)
H=(728*0.30)/2 * 2
BarOrientation=Vertical
[MeterBar4]
Meter=BAR
Group=GroupBarColor
MeasureName=MeasureAudioSmoothed5
X=(8*0.30)R
Y=0
W=(18*0.30)
H=(728*0.30)/2 * 2
BarOrientation=Vertical
[MeterBar5]
Meter=BAR
Group=GroupBarColor
MeasureName=MeasureAudioSmoothed6
X=(8*0.30)R
Y=0
W=(18*0.30)
H=(728*0.30)/2 * 2
BarOrientation=Vertical
[MeterBar6]
Meter=BAR
Group=GroupBarColor
MeasureName=MeasureAudioSmoothed7
X=(8*0.30)R
Y=0
W=(18*0.30)
H=(728*0.30)/2 * 2
BarOrientation=Vertical
[MeterBar7]
Meter=BAR
Group=GroupBarColor
MeasureName=MeasureAudioSmoothed8
X=(8*0.30)R
Y=0
W=(18*0.30)
H=(728*0.30)/2 * 2
BarOrientation=Vertical
[MeterBar8]
Meter=BAR
Group=GroupBarColor
MeasureName=MeasureAudioSmoothed9
X=(8*0.30)R
Y=0
W=(18*0.30)
H=(728*0.30)/2 * 2
BarOrientation=Vertical
[MeterBar9]
Meter=BAR
Group=GroupBarColor
MeasureName=MeasureAudioSmoothed10
X=(8*0.30)R
Y=0
W=(18*0.30)
H=(728*0.30)/2 * 2
BarOrientation=Vertical
[MeterBar10]
Meter=BAR
Group=GroupBarColor
MeasureName=MeasureAudioSmoothed11
X=(8*0.30)R
Y=0
W=(18*0.30)
H=(728*0.30)/2 * 2
BarOrientation=Vertical
[MeterBar11]
Meter=BAR
Group=GroupBarColor
MeasureName=MeasureAudioSmoothed12
X=(8*0.30)R
Y=0
W=(18*0.30)
H=(728*0.30)/2 * 2
BarOrientation=Vertical
[MeterBar12]
Meter=BAR
Group=GroupBarColor
MeasureName=MeasureAudioSmoothed13
X=(8*0.30)R
Y=0
W=(18*0.30)
H=(728*0.30)/2 * 2
BarOrientation=Vertical
[MeterBar13]
Meter=BAR
Group=GroupBarColor
MeasureName=MeasureAudioSmoothed14
X=(8*0.30)R
Y=0
W=(18*0.30)
H=(728*0.30)/2 * 2
BarOrientation=Vertical
[MeterBar14]
Meter=BAR
Group=GroupBarColor
MeasureName=MeasureAudioSmoothed15
X=(8*0.30)R
Y=0
W=(18*0.30)
H=(728*0.30)/2 * 2
BarOrientation=Vertical
[MeterBar15]
Meter=BAR
Group=GroupBarColor
MeasureName=MeasureAudioSmoothed16
X=(8*0.30)R
Y=0
W=(18*0.30)
H=(728*0.30)/2 * 2
BarOrientation=Vertical
[MeterBar16]
Meter=BAR
Group=GroupBarColor
MeasureName=MeasureAudioSmoothed17
X=(8*0.30)R
Y=0
W=(18*0.30)
H=(728*0.30)/2 * 2
BarOrientation=Vertical
[MeterBar17]
Meter=BAR
Group=GroupBarColor
MeasureName=MeasureAudioSmoothed18
X=(8*0.30)R
Y=0
W=(18*0.30)
H=(728*0.30)/2 * 2
BarOrientation=Vertical
[MeterBar18]
Meter=BAR
Group=GroupBarColor
MeasureName=MeasureAudioSmoothed19
X=(8*0.30)R
Y=0
W=(18*0.30)
H=(728*0.30)/2 * 2
BarOrientation=Vertical
[MeterBar19]
Meter=BAR
Group=GroupBarColor
MeasureName=MeasureAudioSmoothed20
X=(8*0.30)R
Y=0
W=(18*0.30)
H=(728*0.30)/2 * 2
BarOrientation=Vertical
[MeterBar20]
Meter=BAR
Group=GroupBarColor
MeasureName=MeasureAudioSmoothed21
X=(8*0.30)R
Y=0
W=(18*0.30)
H=(728*0.30)/2 * 2
BarOrientation=Vertical
[MeterBar21]
Meter=BAR
Group=GroupBarColor
MeasureName=MeasureAudioSmoothed22
X=(8*0.30)R
Y=0
W=(18*0.30)
H=(728*0.30)/2 * 2
BarOrientation=Vertical
[MeterBar22]
Meter=BAR
Group=GroupBarColor
MeasureName=MeasureAudioSmoothed23
X=(8*0.30)R
Y=0
W=(18*0.30)
H=(728*0.30)/2 * 2
BarOrientation=Vertical
[MeterBar23]
Meter=BAR
Group=GroupBarColor
MeasureName=MeasureAudioSmoothed24
X=(8*0.30)R
Y=0
W=(18*0.30)
H=(728*0.30)/2 * 2
BarOrientation=Vertical
[MeterBar24]
Meter=BAR
Group=GroupBarColor
MeasureName=MeasureAudioSmoothed25
X=(8*0.30)R
Y=0
W=(18*0.30)
H=(728*0.30)/2 * 2
BarOrientation=Vertical
[MeterBar25]
Meter=BAR
Group=GroupBarColor
MeasureName=MeasureAudioSmoothed26
X=(8*0.30)R
Y=0
W=(18*0.30)
H=(728*0.30)/2 * 2
BarOrientation=Vertical
[MeterBar26]
Meter=BAR
Group=GroupBarColor
MeasureName=MeasureAudioSmoothed27
X=(8*0.30)R
Y=0
W=(18*0.30)
H=(728*0.30)/2 * 2
BarOrientation=Vertical
[MeterBar27]
Meter=BAR
Group=GroupBarColor
MeasureName=MeasureAudioSmoothed28
X=(8*0.30)R
Y=0
W=(18*0.30)
H=(728*0.30)/2 * 2
BarOrientation=Vertical
[MeterBar28]
Meter=BAR
Group=GroupBarColor
MeasureName=MeasureAudioSmoothed29
X=(8*0.30)R
Y=0
W=(18*0.30)
H=(728*0.30)/2 * 2
BarOrientation=Vertical
[MeterBar29]
Meter=BAR
Group=GroupBarColor
MeasureName=MeasureAudioSmoothed30
X=(8*0.30)R
Y=0
W=(18*0.30)
H=(728*0.30)/2 * 2
BarOrientation=Vertical
[MeterBar30]
Meter=BAR
Group=GroupBarColor
MeasureName=MeasureAudioSmoothed31
X=(8*0.30)R
Y=0
W=(18*0.30)
H=(728*0.30)/2 * 2
BarOrientation=Vertical
[MeterBar31]
Meter=BAR
Group=GroupBarColor
MeasureName=MeasureAudioSmoothed32
X=(8*0.30)R
Y=0
W=(18*0.30)
H=(728*0.30)/2 * 2
BarOrientation=Vertical
[MeterBar32]
Meter=BAR
Group=GroupBarColor
MeasureName=MeasureAudioSmoothed33
X=(8*0.30)R
Y=0
W=(18*0.30)
H=(728*0.30)/2 * 2
BarOrientation=Vertical
[MeterBar33]
Meter=BAR
Group=GroupBarColor
MeasureName=MeasureAudioSmoothed34
X=(8*0.30)R
Y=0
W=(18*0.30)
H=(728*0.30)/2 * 2
BarOrientation=Vertical
[MeterBar34]
Meter=BAR
Group=GroupBarColor
MeasureName=MeasureAudioSmoothed35
X=(8*0.30)R
Y=0
W=(18*0.30)
H=(728*0.30)/2 * 2
BarOrientation=Vertical
[MeterBar35]
Meter=BAR
Group=GroupBarColor
MeasureName=MeasureAudioSmoothed36
X=(8*0.30)R
Y=0
W=(18*0.30)
H=(728*0.30)/2 * 2
BarOrientation=Vertical
[MeterBar36]
Meter=BAR
Group=GroupBarColor
MeasureName=MeasureAudioSmoothed37
X=(8*0.30)R
Y=0
W=(18*0.30)
H=(728*0.30)/2 * 2
BarOrientation=Vertical
[MeterBar37]
Meter=BAR
Group=GroupBarColor
MeasureName=MeasureAudioSmoothed38
X=(8*0.30)R
Y=0
W=(18*0.30)
H=(728*0.30)/2 * 2
BarOrientation=Vertical
[MeterBar38]
Meter=BAR
Group=GroupBarColor
MeasureName=MeasureAudioSmoothed39
X=(8*0.30)R
Y=0
W=(18*0.30)
H=(728*0.30)/2 * 2
BarOrientation=Vertical
[MeterBar39]
Meter=BAR
Group=GroupBarColor
MeasureName=MeasureAudioSmoothed40
X=(8*0.30)R
Y=0
W=(18*0.30)
H=(728*0.30)/2 * 2
BarOrientation=Vertical
[MeterBar40]
Meter=BAR
Group=GroupBarColor
MeasureName=MeasureAudioSmoothed41
X=(8*0.30)R
Y=0
W=(18*0.30)
H=(728*0.30)/2 * 2
BarOrientation=Vertical
[MeterBar41]
Meter=BAR
Group=GroupBarColor
MeasureName=MeasureAudioSmoothed42
X=(8*0.30)R
Y=0
W=(18*0.30)
H=(728*0.30)/2 * 2
BarOrientation=Vertical
[MeterBar42]
Meter=BAR
Group=GroupBarColor
MeasureName=MeasureAudioSmoothed43
X=(8*0.30)R
Y=0
W=(18*0.30)
H=(728*0.30)/2 * 2
BarOrientation=Vertical
[MeterBar43]
Meter=BAR
Group=GroupBarColor
MeasureName=MeasureAudioSmoothed44
X=(8*0.30)R
Y=0
W=(18*0.30)
H=(728*0.30)/2 * 2
BarOrientation=Vertical
[MeterBar44]
Meter=BAR
Group=GroupBarColor
MeasureName=MeasureAudioSmoothed45
X=(8*0.30)R
Y=0
W=(18*0.30)
H=(728*0.30)/2 * 2
BarOrientation=Vertical
[MeterBar45]
Meter=BAR
Group=GroupBarColor
MeasureName=MeasureAudioSmoothed46
X=(8*0.30)R
Y=0
W=(18*0.30)
H=(728*0.30)/2 * 2
BarOrientation=Vertical
[MeterBar46]
Meter=BAR
Group=GroupBarColor
MeasureName=MeasureAudioSmoothed47
X=(8*0.30)R
Y=0
W=(18*0.30)
H=(728*0.30)/2 * 2
BarOrientation=Vertical
[MeterBar47]
Meter=BAR
Group=GroupBarColor
MeasureName=MeasureAudioSmoothed48
X=(8*0.30)R
Y=0
W=(18*0.30)
H=(728*0.30)/2 * 2
BarOrientation=Vertical
[MeterBar48]
Meter=BAR
Group=GroupBarColor
MeasureName=MeasureAudioSmoothed49
X=(8*0.30)R
Y=0
W=(18*0.30)
H=(728*0.30)/2 * 2
BarOrientation=Vertical
[MeterBar49]
Meter=BAR
Group=GroupBarColor
MeasureName=MeasureAudioSmoothed50
X=(8*0.30)R
Y=0
W=(18*0.30)
H=(728*0.30)/2 * 2
BarOrientation=Vertical
[MeterBar50]
Meter=BAR
Group=GroupBarColor
MeasureName=MeasureAudioSmoothed51
X=(8*0.30)R
Y=0
W=(18*0.30)
H=(728*0.30)/2 * 2
BarOrientation=Vertical
[MeterBar51]
Meter=BAR
Group=GroupBarColor
MeasureName=MeasureAudioSmoothed52
X=(8*0.30)R
Y=0
W=(18*0.30)
H=(728*0.30)/2 * 2
BarOrientation=Vertical
[MeterBar52]
Meter=BAR
Group=GroupBarColor
MeasureName=MeasureAudioSmoothed53
X=(8*0.30)R
Y=0
W=(18*0.30)
H=(728*0.30)/2 * 2
BarOrientation=Vertical
[MeterBar53]
Meter=BAR
Group=GroupBarColor
MeasureName=MeasureAudioSmoothed54
X=(8*0.30)R
Y=0
W=(18*0.30)
H=(728*0.30)/2 * 2
BarOrientation=Vertical
[MeterBar54]
Meter=BAR
Group=GroupBarColor
MeasureName=MeasureAudioSmoothed55
X=(8*0.30)R
Y=0
W=(18*0.30)
H=(728*0.30)/2 * 2
BarOrientation=Vertical
[MeterBar55]
Meter=BAR
Group=GroupBarColor
MeasureName=MeasureAudioSmoothed56
X=(8*0.30)R
Y=0
W=(18*0.30)
H=(728*0.30)/2 * 2
BarOrientation=Vertical
[MeterBar56]
Meter=BAR
Group=GroupBarColor
MeasureName=MeasureAudioSmoothed57
X=(8*0.30)R
Y=0
W=(18*0.30)
H=(728*0.30)/2 * 2
BarOrientation=Vertical
[MeterBar57]
Meter=BAR
Group=GroupBarColor
MeasureName=MeasureAudioSmoothed58
X=(8*0.30)R
Y=0
W=(18*0.30)
H=(728*0.30)/2 * 2
BarOrientation=Vertical
[MeterBar58]
Meter=BAR
Group=GroupBarColor
MeasureName=MeasureAudioSmoothed59
X=(8*0.30)R
Y=0
W=(18*0.30)
H=(728*0.30)/2 * 2
BarOrientation=Vertical
[MeterBar59]
Meter=BAR
Group=GroupBarColor
MeasureName=MeasureAudioSmoothed60
X=(8*0.30)R
Y=0
W=(18*0.30)
H=(728*0.30)/2 * 2
BarOrientation=Vertical
[MeterBar60]
Meter=BAR
Group=GroupBarColor
MeasureName=MeasureAudioSmoothed61
X=(8*0.30)R
Y=0
W=(18*0.30)
H=(728*0.30)/2 * 2
BarOrientation=Vertical
[MeterBar61]
Meter=BAR
Group=GroupBarColor
MeasureName=MeasureAudioSmoothed62
X=(8*0.30)R
Y=0
W=(18*0.30)
H=(728*0.30)/2 * 2
BarOrientation=Vertical
[MeterBar62]
Meter=BAR
Group=GroupBarColor
MeasureName=MeasureAudioSmoothed63
X=(8*0.30)R
Y=0
W=(18*0.30)
H=(728*0.30)/2 * 2
BarOrientation=Vertical
[MeterBar63]
Meter=BAR
Group=GroupBarColor
MeasureName=MeasureAudioSmoothed64
X=(8*0.30)R
Y=0
W=(18*0.30)
H=(728*0.30)/2 * 2
BarOrientation=Vertical
[MeterBar64]
Meter=BAR
Group=GroupBarColor
MeasureName=MeasureAudioSmoothed65
X=(8*0.30)R
Y=0
W=(18*0.30)
H=(728*0.30)/2 * 2
BarOrientation=Vertical
[MeterBar65]
Meter=BAR
Group=GroupBarColor
MeasureName=MeasureAudioSmoothed66
X=(8*0.30)R
Y=0
W=(18*0.30)
H=(728*0.30)/2 * 2
BarOrientation=Vertical
[MeterBar66]
Meter=BAR
Group=GroupBarColor
MeasureName=MeasureAudioSmoothed67
X=(8*0.30)R
Y=0
W=(18*0.30)
H=(728*0.30)/2 * 2
BarOrientation=Vertical
[MeterBar67]
Meter=BAR
Group=GroupBarColor
MeasureName=MeasureAudioSmoothed68
X=(8*0.30)R
Y=0
W=(18*0.30)
H=(728*0.30)/2 * 2
BarOrientation=Vertical
[MeterBar68]
Meter=BAR
Group=GroupBarColor
MeasureName=MeasureAudioSmoothed69
X=(8*0.30)R
Y=0
W=(18*0.30)
H=(728*0.30)/2 * 2
BarOrientation=Vertical
[MeterBar69]
Meter=BAR
Group=GroupBarColor
MeasureName=MeasureAudioSmoothed70
X=(8*0.30)R
Y=0
W=(18*0.30)
H=(728*0.30)/2 * 2
BarOrientation=Vertical
[MeterBar70]
Meter=BAR
Group=GroupBarColor
MeasureName=MeasureAudioSmoothed71
X=(8*0.30)R
Y=0
W=(18*0.30)
H=(728*0.30)/2 * 2
BarOrientation=Vertical
[MeterBar71]
Meter=BAR
Group=GroupBarColor
MeasureName=MeasureAudioSmoothed72
X=(8*0.30)R
Y=0
W=(18*0.30)
H=(728*0.30)/2 * 2
BarOrientation=Vertical
[MeterBar72]
Meter=BAR
Group=GroupBarColor
MeasureName=MeasureAudioSmoothed73
X=(8*0.30)R
Y=0
W=(18*0.30)
H=(728*0.30)/2 * 2
BarOrientation=Vertical
[MeterBar73]
Meter=BAR
Group=GroupBarColor
MeasureName=MeasureAudioSmoothed74
X=(8*0.30)R
Y=0
W=(18*0.30)
H=(728*0.30)/2 * 2
BarOrientation=Vertical
[MeterBar74]
Meter=BAR
Group=GroupBarColor
MeasureName=MeasureAudioSmoothed75
X=(8*0.30)R
Y=0
W=(18*0.30)
H=(728*0.30)/2 * 2
BarOrientation=Vertical
[MeterBar75]
Meter=BAR
Group=GroupBarColor
MeasureName=MeasureAudioSmoothed76
X=(8*0.30)R
Y=0
W=(18*0.30)
H=(728*0.30)/2 * 2
BarOrientation=Vertical
[MeterBar76]
Meter=BAR
Group=GroupBarColor
MeasureName=MeasureAudioSmoothed77
X=(8*0.30)R
Y=0
W=(18*0.30)
H=(728*0.30)/2 * 2
BarOrientation=Vertical
[MeterBar77]
Meter=BAR
Group=GroupBarColor
MeasureName=MeasureAudioSmoothed78
X=(8*0.30)R
Y=0
W=(18*0.30)
H=(728*0.30)/2 * 2
BarOrientation=Vertical
[MeterBar78]
Meter=BAR
Group=GroupBarColor
MeasureName=MeasureAudioSmoothed79
X=(8*0.30)R
Y=0
W=(18*0.30)
H=(728*0.30)/2 * 2
BarOrientation=Vertical
[MeterBar79]
Meter=BAR
Group=GroupBarColor
MeasureName=MeasureAudioSmoothed80
X=(8*0.30)R
Y=0
W=(18*0.30)
H=(728*0.30)/2 * 2
BarOrientation=Vertical
[MeterBar80]
Meter=BAR
Group=GroupBarColor
MeasureName=MeasureAudioSmoothed81
X=(8*0.30)R
Y=0
W=(18*0.30)
H=(728*0.30)/2 * 2
BarOrientation=Vertical
[MeterBar81]
Meter=BAR
Group=GroupBarColor
MeasureName=MeasureAudioSmoothed82
X=(8*0.30)R
Y=0
W=(18*0.30)
H=(728*0.30)/2 * 2
BarOrientation=Vertical
[MeterBar82]
Meter=BAR
Group=GroupBarColor
MeasureName=MeasureAudioSmoothed83
X=(8*0.30)R
Y=0
W=(18*0.30)
H=(728*0.30)/2 * 2
BarOrientation=Vertical
[MeterBar83]
Meter=BAR
Group=GroupBarColor
MeasureName=MeasureAudioSmoothed84
X=(8*0.30)R
Y=0
W=(18*0.30)
H=(728*0.30)/2 * 2
BarOrientation=Vertical
[MeterBar84]
Meter=BAR
Group=GroupBarColor
MeasureName=MeasureAudioSmoothed85
X=(8*0.30)R
Y=0
W=(18*0.30)
H=(728*0.30)/2 * 2
BarOrientation=Vertical
[MeterBar85]
Meter=BAR
Group=GroupBarColor
MeasureName=MeasureAudioSmoothed86
X=(8*0.30)R
Y=0
W=(18*0.30)
H=(728*0.30)/2 * 2
BarOrientation=Vertical
[MeterBar86]
Meter=BAR
Group=GroupBarColor
MeasureName=MeasureAudioSmoothed87
X=(8*0.30)R
Y=0
W=(18*0.30)
H=(728*0.30)/2 * 2
BarOrientation=Vertical
[MeterBar87]
Meter=BAR
Group=GroupBarColor
MeasureName=MeasureAudioSmoothed88
X=(8*0.30)R
Y=0
W=(18*0.30)
H=(728*0.30)/2 * 2
BarOrientation=Vertical
[MeterBar88]
Meter=BAR
Group=GroupBarColor
MeasureName=MeasureAudioSmoothed89
X=(8*0.30)R
Y=0
W=(18*0.30)
H=(728*0.30)/2 * 2
BarOrientation=Vertical
[MeterBar89]
Meter=BAR
Group=GroupBarColor
MeasureName=MeasureAudioSmoothed90
X=(8*0.30)R
Y=0
W=(18*0.30)
H=(728*0.30)/2 * 2
BarOrientation=Vertical
[MeterBar90]
Meter=BAR
Group=GroupBarColor
MeasureName=MeasureAudioSmoothed91
X=(8*0.30)R
Y=0
W=(18*0.30)
H=(728*0.30)/2 * 2
BarOrientation=Vertical
[MeterBar91]
Meter=BAR
Group=GroupBarColor
MeasureName=MeasureAudioSmoothed92
X=(8*0.30)R
Y=0
W=(18*0.30)
H=(728*0.30)/2 * 2
BarOrientation=Vertical
[MeterBar92]
Meter=BAR
Group=GroupBarColor
MeasureName=MeasureAudioSmoothed93
X=(8*0.30)R
Y=0
W=(18*0.30)
H=(728*0.30)/2 * 2
BarOrientation=Vertical
[MeterBar93]
Meter=BAR
Group=GroupBarColor
MeasureName=MeasureAudioSmoothed94
X=(8*0.30)R
Y=0
W=(18*0.30)
H=(728*0.30)/2 * 2
BarOrientation=Vertical
[MeterBar94]
Meter=BAR
Group=GroupBarColor
MeasureName=MeasureAudioSmoothed95
X=(8*0.30)R
Y=0
W=(18*0.30)
H=(728*0.30)/2 * 2
BarOrientation=Vertical
[MeterBar95]
Meter=BAR
Group=GroupBarColor
MeasureName=MeasureAudioSmoothed96
X=(8*0.30)R
Y=0
W=(18*0.30)
H=(728*0.30)/2 * 2
BarOrientation=Vertical
[MeterBar96]
Meter=BAR
Group=GroupBarColor
MeasureName=MeasureAudioSmoothed97
X=(8*0.30)R
Y=0
W=(18*0.30)
H=(728*0.30)/2 * 2
BarOrientation=Vertical
[MeterBar97]
Meter=BAR
Group=GroupBarColor
MeasureName=MeasureAudioSmoothed98
X=(8*0.30)R
Y=0
W=(18*0.30)
H=(728*0.30)/2 * 2
BarOrientation=Vertical
[MeterBar98]
Meter=BAR
Group=GroupBarColor
MeasureName=MeasureAudioSmoothed99
X=(8*0.30)R
Y=0
W=(18*0.30)
H=(728*0.30)/2 * 2
BarOrientation=Vertical